baseURL = 'https://pjeje.github.io/dicas/'
languageCode = 'pt-br'
title = 'PJe Dicas'
theme = "hugo-theme-learn"
defaultContentLanguage = "pt"
defaultContentLanguageInSubdir = false
metaDataFormat = "yaml"
canonifyURLs = true


[params]
themeVariant = "blue"
editURL = "https://github.com/PJeJE/dicas/edit/master/content/"
description = "PJe Dicas v2.0"
author = "ASPJE"
showVisitedLinks = true
disableBreadcrumb = false
disableNextPrev = false
disableLandingPageButton = true
disableMermaid = false
ordersectionsby = "weight"
customMermaidURL = "https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js"
titleSeparator = "::"
custom_css = ["css/dicas.css"]

[outputs]
home = ["HTML", "RSS", "JSON"]

[[menu.shortcuts]]
name = '<i class="fas fa-tag"></i> Formulário SGT'
identifier = "sgt"
url = "https://docs.google.com/forms/d/e/1FAIpQLSf8t7ytC4vzxM2e6GEUtN_au28whzhE7YQ9ZE7-pkl3rMiTng/viewform?embedded=true"
weight = 9

[[menu.shortcuts]]
name = '<i class="fas fa-pen"></i> Participe!'
identifier = "participe"
url = "https://docs.google.com/forms/d/e/1FAIpQLSfxRFWQlGyeRiFW4ZKZQDvc8ofZc44nqFrsyn5m4ll3oR9ffw/viewform?embedded=true"
weight = 10